serverless/components

registry/aws-lambda/index.js

Removes the unnecessary role suffix which makes the name longer as it needs to be (and therefore might introduce resource name validation errors in the future).
@brianneisler discovered it in https://github.com/serverless/serverless-components/pull/89#pullrequestreview-107124426
```yml
components:
myFunction:
type: aws-lambda
inputs:
memory: 512
timeout: 10
handler: handler.handler
```
1. Run `components deploy`
1. See that the role name is already suffixed with the function name (which is unique in our case)
1. Run `components remove`

Remove unnecessary suffix for auto-generated aws-lambda role

---

registry/aws-apigateway/index.js
registry/aws-apigateway/utils.js
registry/aws-apigateway/utils.test.js

Fixes a state issue where the url disappeared fromt he state when the `rest-api` routes were updating after a successfull deploy.
Use this service:
```yml
components:
myFunction:
type: aws-lambda
inputs:
memory: 512
timeout: 10
handler: handler.handler
role:
arn: ${myRole.arn}
myRole:
type: aws-iam-role
inputs:
service: lambda.amazonaws.com
myRestApi:
type: rest-api
inputs:
gateway: aws-apigateway
routes:
/foo:
get:
function: ${myFunction}
cors: true
```
1. Run `components deploy`
1. Inspect the `state.json` file content and see that the base url is saved at the `url` property
1. Uncomment the `/bar` route definition
1. Run `components deploy`
1. Inspect the `state.json` file content and see that the base url is still saved at the `url` property

Add URL to outputs when updating API Gateway

---

registry/aws-lambda/index.js
registry/aws-lambda/pack.js
registry/aws-lambda/pack.test.js
registry/aws-lambda/package-lock.json
registry/aws-lambda/package.json

Refactor the way we zip to use async only code and waiting for the writeStream to be opened before piping data into it.
`deploy`, `invoke`, re-`deploy` and re-`invoke` the following service:
```yml
components:
myFunction:
type: aws-lambda
inputs:
memory: 512
timeout: 10
handler: handler.handler
role:
arn: ${myRole.arn}
myRole:
type: aws-iam-role
inputs:
service: lambda.amazonaws.com
```

Refactor aws-lambda zipping functionality

---

examples/basic/serverless.yml

Removes the set names to avoid name collisions when deploying the service from scratch and other resources deployed to AWS already use this name.
1. `cd` into `examples/basic`
1. Run `components deploy`

Remove name properties from basic example to avoid name collisions

---

registry/aws-apigateway/utils.js
registry/aws-apigateway/utils.test.js

Adds a trailing slash to the generated URLs (as reported by @ac360).
Deploy the `retail-app` example and see that the broken URLs are working fine again.

Add trailing slash to generated URLs

---

registry/aws-dynamodb/index.js

Removes a misleading DDB log statement that tables(s) are created.
Deploy the `retail-app` example and follow the logs. For each table you should see separate log messages that they table is created. The overall message which says that table(s) are being created shouldn't be visible anymore.

Remove misleading DynamoDB table log statement

---

src/utils/components/requireFns.js
src/utils/components/requireFns.test.js

Detect when dependencies are not installed and show an appropriate error message.
The service used to test this functionality.
```yml
type: test
components:
myComponent:
type: some-component
```
```js
// example/test/index.js
const express = require('express') // NOTE: don't install this
async function deploy(inputs, context) {
console.log('deploying...')
}
module.exports = {
deploy
}
```
Used to validate that entry-point-less services still works.
```
type: some-component
components:
myTestFunc:
type: tests-integration-function-mock
inputs:
name: some-name
role: some-role
```
Run `components deploy` in the `example/test` directory. You should see an error message saying that `express` is not installed. You shouldn't see an error message that an `index.js` or other entry-point file for …

Throw error when detecting non-installed dependencies

---

src/utils/components/executeComponent.js
tests/integration/await-child-components.test.js
tests/integration/programmatic-usage.test.js
tests/integration/simple.test.js

Fixes awaited child components carrying out-of-date state: https://serverlessteam.atlassian.net/browse/SC-197
* Cherry-pick https://github.com/serverless/serverless-components/commit/6e94454c938dc1b628b69124a38a71855937d2b1
* Deploy examples/await-state
* See `CHILD STATE: {count:1}` on the very first deploy

Await child state

---

examples/basic/README.md
examples/retail-app/README.md

Remove the `rollback` support references in the documentation since it's not supported right now.
Just glance over the docs.

Remove rollback references in docs

---

README.md
registry/aws-lambda/pack.test.js

Quick follow-up PR of https://github.com/serverless/serverless-components/pull/115 which ensures async-only code-usage, formatting according to prettier, doc updates and updated assertions.
Tests should still pass.

Refactor pack tests

---

src/utils/components/executeComponent.js
src/utils/components/executeComponent.test.js

Skips removals based on empty states which caused the framework to error-out in the past.
Deploy the `basic` example app. Remove it and run `remove` again.

Skip empty state removals

---

src/utils/dag/buildGraph.js
src/utils/dag/detectCircularDeps.js
src/utils/dag/detectCircularDeps.test.js
src/utils/dag/index.js
src/utils/misc/forEachIndexed.js
src/utils/misc/index.js

Closes SC-211
Adds the functionality to detect circular dependencies in the DAG.
Use the following service and try to deploy it. You should see an error popping up which explains where the circular dependency was found.
```yml
type: circular-dependencies
components:
myLambda:
type: aws-lambda
inputs:
handler: code/index.handler
name: ${lambdaRole.name}
memory: 512
timeout: 60
role:
arn: ${lambdaRole.arn}
lambdaRole:
type: aws-iam-role
inputs:
name: ${myLambda.name}
service: lambda.amazonaws.com
```

Add circular dependency detection in DAG

---

examples/basic/serverless.yml
registry/aws-iam-role/index.js
registry/aws-iam-role/index.test.js

1. deploy an IAM component
2. copy the state
3. run remove the IAM component
4. after the remove is complete replace the state file with the original copy.
5. run remove again.
6. The removal should not throw an error and should complete successfully.
7. The state file should be updated to reflect the component has been removed.

Make IAM remove function idempotent

---

package.json
scripts/cleanse.js
scripts/postinstall.js

This PR removes the reuse of stdio between all child processes which slows down the installs significantly. It also adds a cleanse script that can be used to wipe out all node_modules folders when necessary.
For reference this issue is documented here https://github.com/nodejs/node/issues/3429

Fix issues in postinstall causing significant slow down in the install time

---

src/run.js
src/run.test.js
src/utils/dag/executeGraph.js
src/utils/dag/executeGraph.test.js
src/utils/misc/handleSignalEvents.js
src/utils/misc/handleSignalEvents.test.js
src/utils/misc/index.js

Implements the functionality to check again whether the user wants to force an exit when using `ctrl + c`.
Closes SC-208
Closes SC-223
Deploy a service which might take some time to finish and hit `ctrl + c`. You should see a warning. Hitting `ctrl + c` again should force an exit.

Add signal event (SIGINT, SIGTERM, SIGBREAK) handling

---

registry/aws-route53/index.js
registry/aws-route53/indext.test.js

1. deploy component
2. copy the state
3. run remove the component
4. after the remove is complete replace the state file with the original copy.
5. run remove again.
6. The removal should not throw an error and should complete successfully.
7. The state file should be updated to reflect the component has been removed.

Make Route53 component remove function idempotent

---

registry/aws-cloudfront/index.js
registry/aws-cloudfront/index.test.js
src/utils/components/executeComponent.js
src/utils/components/executeComponent.test.js

1. deploy the component
2. copy the state
3. run remove the component
4. after the remove is complete replace the state file with the original copy.
5. run remove again.
6. The removal should not throw an error and should complete successfully.
7. The state file should be updated to reflect the component has been removed.

Make cloudfront component removal idempotent

---

.appveyor.yml

Adds AppVeyor to our CI tooling so that we can run the tests for Windows systems as well.
Closes SC-242
---
I tried to add the addon / app to the GitHub repository, but it looks like I'm not authorized to do that. Would be nice if @brianneisler could take a quick look at it and set it up (Aside: we already did the same for the `serverless/serverless` repository).

Add AppVeyor CI support

---

registry/aws-cloudfront/index.test.js
registry/aws-iam-role/index.test.js
registry/aws-lambda/index.test.js
registry/aws-route53/indext.test.js
registry/aws-s3-bucket/index.test.js

AWS tests were previously impacting each other and cannot be run individually. This PR fixes this by clearing the mocks after each test.

Fixed AWS Tests

---

registry/tests-invalid-variables-usage/index.js
registry/tests-invalid-variables-usage/serverless.yml
src/utils/components/getComponent.js
src/utils/components/getComponent.test.js
src/utils/variables/index.js
src/utils/variables/validateVarsUsage.js
src/utils/variables/validateVarsUsage.test.js

Validates variables usage so that it throws an error if serverless variables are used in the `type` or `version` property.
Closes SC-259
Use the following service and run `components deploy`. You should see an error saying that you cannot use variables in the "type" or "version" property.
```yml
type: ${env.COMPONENT_TYPE}
version: ${env.COMPONENT_VERSION}
components:
myRole:
type: aws-iam-role
inputs:
service: lambda.amazonaws.com
```

Validate variables usage

---

.codecov.yml
.travis.yml
package.json

Adds Codecov support so that we can see the actual code coverage and add guards to prevent untested code from being merged.
Closes SC-236
---
I tried to add the GitHub integration, but it looks like I'm not authorized to do that. @brianneisler it would be nice if you could add that to the repo so that we can have PR / Branch checks.

Add Codecov support

---

docker-compose.yml
package-lock.json
package.json

Automatically runs ESLint and Prettier on every Git commit, ensuring that only linted and prettified files are pushed.
Closes SC-244
Closes SC-245
Check out the branch. Create a new branch based on this branch. Modify a .js file (add ESLint violations and format it slightly). Stage the file and commit it. The pre commit checks should kick in --> ESLint and Prettier should auto-fix violations when possible.

Auto-run ESLint and Prettier on every Git commit

---

registry/aws-dynamodb/serverless.yml

This Pull Request fixes a minor typo in the description field for the Dynamo DB component
* Line 13 should now read
```yaml
DynamoDB Table Definitions
```

fix typo in Dynamo DB component serverless.yml

---

tests/integration/await-child-components.test.js
tests/integration/programmatic-usage.test.js
tests/integration/simple.test.js

Tests keep timing out on travis. Extended the timeouts.

Extend timeout for integration tests since they keep timing out

---

src/utils/log.js
src/utils/log.test.js

Fixes the issues where logs were not printed to the console (`stdin` was used rather than `stdout).
Closes SC-271
Just take a look at the added test file.

Fix log function

---

.eslintrc.js
registry/aws-cloudfront/index.js
registry/s3-sync/index.js
registry/s3-website-config/index.js

In https://github.com/serverless/components/pull/205 we've replaced the "airbnb" liniting rules with "prettier" linting rules to tightly integrate both, ESLint as well as Prettier.
However some really helpful rules from the airbnb plugin are missing.
I added those via this PR. Might add more via other PRs if something else is missing.

Extend linting rules

---

package-lock.json
package.json
registry/buildComponents.js
registry/package-lock.json
registry/package.json
registry/rest-api/package-lock.json
registry/tests-integration-await-child-components/package-lock.json
registry/watch.js

This PR adds Babel watch script to the registry. It should ease the component development when running test deployments with development version.
* In registry directory, run `npm run watch` to watch all components
* `npm run watch -- aws-s3-bucket eventgateway` to only watch specified components

Add Babel watch script to the registry

---

.appveyor.yml
.babelrc
.travis.yml
registry/.babelrc
registry/postinstall.js
scripts/postinstall.js

Our tests are flaky, slow and some npm packages we rely on were updated and break with Node.js 4. Removing Node.js 4 support since it was sunsetted and AWS Lambda doesn't support the creation of Node.js 4 runtimes anymore.

Remove Node.js 4 support

---

package.json
scripts/create-component.js

This PR adds script that creates an empty component boilerplate to the registry.
Run `npm run create:component my-component` and the script should create a new component to the registry directory with name `my-component`.
The new component directory should contain package.json, readme.md, serverless.yml, src/index.js, and src/index.test.js files.

Create a new component script

---

README.md

This redirect will make it easier to manage this link in the future.

Update slack link to a redirect through serverless.com

---

README.md
registry/serverless-eventgateway-function/README.md
registry/serverless-eventgateway-function/package-lock.json
registry/serverless-eventgateway-function/package.json
registry/serverless-eventgateway-function/serverless.yml
registry/serverless-eventgateway-function/src/index.js
registry/serverless-eventgateway-function/src/index.test.js
registry/serverless-eventgateway-function/src/utils/createFunction.js
registry/serverless-eventgateway-function/src/utils/createFunction.test.js
registry/serverless-eventgateway-function/src/utils/deleteFunction.js
registry/serverless-eventgateway-function/src/utils/deleteFunction.test.js
registry/serverless-eventgateway-function/src/utils/index.js
registry/serverless-eventgateway-function/src/utils/updateFunction.js
registry/serverless-eventgateway-function/src/utils/updateFunction.test.js

This adds the `serverless-eventgateway-function` component to the registry.
Basic usage looks like this:
```yml
type: eg-function-test
components:
eventGatewayFunction:
type: serverless-eventgateway-function
inputs:
space: acme-marketing-space
accessKey: s0m34c355k3y
url: http://localhost
functionId: sendEmail
functionType: awslambda
provider:
arn: arn:aws:lambda:us-east-1:12345:function:example
region: us-east-1
```

Add Event Gateway Function component

---

README.md
registry/serverless-eventgateway-event-type/README.md
registry/serverless-eventgateway-event-type/package-lock.json
registry/serverless-eventgateway-event-type/package.json
registry/serverless-eventgateway-event-type/serverless.yml
registry/serverless-eventgateway-event-type/src/index.js
registry/serverless-eventgateway-event-type/src/index.test.js
registry/serverless-eventgateway-event-type/src/utils/createEventType.js
registry/serverless-eventgateway-event-type/src/utils/createEventType.test.js
registry/serverless-eventgateway-event-type/src/utils/deleteEventType.js
registry/serverless-eventgateway-event-type/src/utils/deleteEventType.test.js
registry/serverless-eventgateway-event-type/src/utils/index.js
registry/serverless-eventgateway-event-type/src/utils/updateEventType.js
registry/serverless-eventgateway-event-type/src/utils/updateEventType.test.js

This adds the `serverless-eventgateway-event-type` component to the registry.
Basic usage looks like this:
```yml
type: eg-event-type-test
components:
eventGatewayEventType:
type: serverless-eventgateway-event-type
inputs:
space: acme-marketing-space
accessKey: s0m34c355k3y
url: 'http://localhost'
name: user.created
```

Add Event Gateway Event Type component

---

README.md
registry/serverless-eventgateway-cors/README.md
registry/serverless-eventgateway-cors/package-lock.json
registry/serverless-eventgateway-cors/package.json
registry/serverless-eventgateway-cors/serverless.yml
registry/serverless-eventgateway-cors/src/index.js
registry/serverless-eventgateway-cors/src/index.test.js
registry/serverless-eventgateway-cors/src/utils/createCors.js
registry/serverless-eventgateway-cors/src/utils/createCors.test.js
registry/serverless-eventgateway-cors/src/utils/deleteCors.js
registry/serverless-eventgateway-cors/src/utils/deleteCors.test.js
registry/serverless-eventgateway-cors/src/utils/index.js
registry/serverless-eventgateway-cors/src/utils/updateCors.js
registry/serverless-eventgateway-cors/src/utils/updateCors.test.js

This adds the `serverless-eventgateway-cors` component to the registry.
Basic usage looks like this:
```yml
type: eg-cors-test
components:
eventGatewayCors:
type: serverless-eventgateway-cors
inputs:
space: acme-marketing-space
accessKey: s0m34c355k3y
url: 'http://localhost'
path: /my-path
method: POST
allowedOrigins:
- 'http://*.domain.com'
allowedMethods:
- POST
- GET
allowedHeaders:
- Origin
- Accept
allowCredentials: false
```

Add Event Gateway CORS component

---

registry/AwsProvider/README.md
registry/AwsProvider/serverless.yml

Allows you to omit the credentials in an `AwsProvider` instance, instead allowing `aws-sdk` to pull the creds from `~/.aws/credentials`.
As trivial as this change looks, it works because when credentials aren't defined in the `aws-sdk` config object, it reads the creds from disk
* delete the credentials section in sls-web-apps's `AwsProvider` section https://github.com/serverless/serverless-web-application/blob/master/serverless.yml#L35
* deploy sls-web-app

Don't require credentials in AwsProvider

---

registry/AwsProvider/README.md

Types that are to be instantiated _must_ have `inputs`. Also realized that the `inputs` in the other examples weren't properly indented.

Fix AwsProvider README examples

---

__mocks__/aws-sdk.js
registry/AwsEventsRule/src/index.js
registry/AwsEventsRule/src/index.test.js
registry/AwsIamPolicy/src/index.js
registry/AwsIamPolicy/src/index.test.js
registry/AwsIamRole/src/index.js
registry/AwsIamRole/src/index.test.js
registry/AwsLambdaFunction/src/index.js
registry/AwsLambdaFunction/src/index.test.js
registry/AwsS3Bucket/src/indext.test.js
registry/AwsS3Bucket/src/utils/deleteBucket.js
registry/AwsS3Website/src/index.js
registry/AwsS3Website/src/index.test.js
registry/AwsSnsSubscription/src/index.js
registry/AwsSnsSubscription/src/index.test.js
registry/AwsSnsTopic/src/index.js
registry/AwsSnsTopic/src/index.test.js

This PRs adds idempotency guarantees on removals for AWS components.
The implementation is based on the error codes AWS provides. This way we're not checking error-messages anymore which might be changed in the future. Unit tests were added to ensure the functionality.
**Note 1:** Right now the `AwsApiGateway` component was not updates since the API docs and its error codes are unavailable ATM --> https://docs.aws.amazon.com/goto/WebAPI/apigateway-2015-07-09/DeleteRestApi
**Note 2:** I've implemented this against the AWS SDK docs and checked the error structure (how to access the `code`) via `AwsIamRole` manually. Assume that not all components were tested manually and that the code I've picked from the docs might be wrong (updating this is a no-brainer though).
AWS components updated: …

Add remove idempotency for AWS components

---

registry/AwsIamRole/serverless.yml
registry/AwsIamRole/src/index.js
registry/AwsIamRole/src/index.test.js

Adds a validation which checks for the length of tha `AwsIamRole` name property.
/cc @sebito91

AwsIamRole name length validation

---

.travis.yml
__mocks__/aws-sdk.js
registry/AwsIamRole/serverless.yml
registry/AwsIamRole/src/index.js
registry/AwsIamRole/src/index.test.js
registry/AwsLambdaFunction/src/index.js
registry/AwsLambdaFunction/src/index.test.js
registry/AwsProvider/src/index.js

* AwsIamRole now supports being given an inline policy in addition to one with an ARN
* AwsIamRole no longer defaults to attaching the admin policy
* AwsLambdaCompute now specifies the minimum inline role that a lambda needs
* doesn't currently set account Id in the ARN, not sure if that's available in this context?
* run `components deploy` in a service using AwsLambdaCompute without roles specified
* in the AWS console check that the roles created have an inline policy granting perms to create & write to a the right cloudwatch log group and not have the managed AdministratorAccess policy attached.

Inline IamRole Policies & better default creation for lambdas

---

registry/AwsSnsTopic/src/index.js
registry/AwsSnsTopic/src/index.test.js

Fixes a bug where SNS topics are constantly re-deployed if if they haven't changed.
Added a regression test to ensure that this bug won't happen again in the near future.
From a DM with @raeesbhatti:
> The issue is that since we're using stuff like `{ foo = [] }` in function arguments we're setting defaults when values are not provided. This was the case for `deliveryStatusAttributes`. If it's not set via `inputs` it's `undefined`. However it's re-assigned to `[]` in the other functions it runs through. This causes `prevInstance.inputs.deliveryStatusAttributes` to have the value `[]` whereas inputs has `undefined`. This in turn causes the check if the inputs changed to return true every time, hence causing a re-deploy.
/cc @shortjared @mthenw

Fix AwsSnsTopic check for changes

---

registry/Service/src/index.js
registry/Service/src/index.test.js

Fixes the bug where services without `components` defined couldn't run `info`.
/cc @ac360

Fix info support for services without components

---

src/utils/context/newContext.js
src/utils/context/newContext.test.js
src/utils/dag/deployGraph.test.js
src/utils/dag/execGraph.js
src/utils/dag/execGraph.test.js
src/utils/dag/removeGraph.test.js
src/utils/index.test.js
src/utils/logging/error.js
src/utils/logging/error.test.js
src/utils/logging/index.js
src/utils/logging/info.js
src/utils/logging/info.test.js
src/utils/logging/warn.js
src/utils/logging/warn.test.js

This PR adds the change that the `context.log` function is replaced with `context.debug` before it's passed into components.
With this change verbose component outputs are hidden by default and only visible if one runs the component command with the help of the `--debug` flag (such as `components deploy --debug`). All system logs are still shown by default.
Additionally other log level were implemented which are accessible via `context.console.*` (they follow the JavaScript `console.*` pattern). This means that e.g. component authors can use `context.console.error` to show an error or `context.console.log` to force a log message to be shown.
Here's an example which shows how this can be used as a component author:
```js
const NestedService = {
shouldDeploy(prevInstance) {
return 'deploy' …
```

Silent component logging

---

__mocks__/aws-sdk.js
registry/AwsS3Bucket/src/index.js
registry/AwsS3Bucket/src/indext.test.js
tests/integration/library-usage.test.js
tests/integration/library-usage/deploy/serverless.yml
tests/integration/library-usage/remove/serverless.yml

- make first deployment of new s3 bucket
- delete `.serverless` folder
- run deploy again -> framework will not deploy as no changes happened
- delete bucket from s3 console
- run deploy again -> framework will create bucket again even though it exists in `.serverless` folder

Adds support for idempotency for AwsS3Bucket deployment

---

src/utils/dag/execGraph.js
src/utils/dag/execGraph.test.js
src/utils/dag/index.js
src/utils/dag/logStatus.js
src/utils/dag/logStatus.test.js

This adds the functionality to log what the core system is deploying / removing while walking through the graph.
Only inputs / paramsters which are `required` are shown so that user can determine which component was deployed / removed exactly without being overwhelmed by the full-blown parameter list.
Tests were added to cover the proper functionality.
The output looks like this:
```
[components/examples/test-components]$ ../../bin/components deploy
Loading plugins...
Deploy running...
Deploying "NestedService" with parameters:
"name":"foo"
Deploying "ComponentsTest" 
Deployment complete!
Getting info...
ComponentsTest - Service
|- NestedService - NestedService
name: NestedService
version: 0.3.0
[components/examples/test-components]$ ../../bin/components deploy
Loading plugins...
Deploy …
```

Graph operation status reporting

---

__mocks__/aws-sdk.js
registry/AwsIamPolicy/src/index.js
registry/AwsIamPolicy/src/index.test.js

Adds sync method to AwsIamPolicy, and improves removal to take policy versions into consideration (necessary if users made changes to the policy in the AWS console)

Adds support for idempotency to AwsIamPolicy

---

src/utils/dag/logStatus.js
src/utils/dag/logStatus.test.js

This omits our internal types from being logged (such as `AwsProvider`) since those a quite verbose when logging and cause the `JSON.stringify` command to fail due to deeply nested structures.

Omit internal types during status logging

---

registry/AwsProvider/src/index.js
registry/AwsProvider/src/index.test.js

This needs to be in place so that the component `sync` function works since we're using `provider` there.

Auto resolve credentials in AwsProvider

---

src/utils/dag/logStatus.js

Fixes an issue where the status logging bailed when a JSON has circular references.
This is a catch-all since I already fixed this behavior for components, but it seems like there are more datastructures which can cause these issues.
/cc @eahefnawy

Add logStatus catch all logic for circular JSON objects

---

README.md

Fix the "Getting started" examples. In my experience I had to export the component to make things work.
I hope this is a change that makes sense, please review as I am no NodeJS expert :)

Document that components need to be exported

---

src/Component.js

This PR fixes a bug with built-in class methods arguments forwarding. The way they were implemented would only consume the first argument which would cause wrong behavior on methods like `load` (which accepts 2 arguments).
This fix is required for PR [serverless/template#8](https://github.com/serverless/template/pull/8) to work properly (without it, custom methods will not have access to the component state).
@eahefnawy as always, please review and send feedback if any changes are necessary :)

Consume all method arguments when calling built-in methods.

---

package.json

Package name doesn't reflect repository name as on GitHub, so it's hard to seclude that information on your own (especially when confusing old core repositories are still public on github)

Configure "repository" in package.json

---

templates/fullstack-application/dashboard/package.json
templates/website/package.json

When testing them locally, I've approached errors as `Cannot find module '@babel/plugin-transform-runtime'`  and  `Cannot resolve dependency '@babel/runtime/regenerator'`
Parcel adds some missing dependencies to package.json on it's own, but for some reason it stumbles with above errors if those are not listed

Fix templates that involve parcel builds

---

src/cli/commands/create.js
src/cli/commands/dev.js
src/cli/commands/info.js
src/cli/commands/login.js
src/cli/commands/login2.js
src/cli/commands/registry.js
src/cli/commands/run.js
src/cli/commands/utils.js
src/cli/utils.js

Goal is to use two different SDK's conditionally, and to separate completely work on Tencent dedicated commands from AWS commands.
This PR, secludes utils that are specific to AWS SDK, into it's commands folder.
Having that @hkbarton will follow with next PR which will introduce a `commands-cn` folder which will serve command dedicated for Tencent platform
Additionally I've configured `IS_IN_CHINA` constant into utils, to be used for chinese users detection

Seclude command specific utils (to allow china SDK separation)

---

src/cli/utils.js

Initially I blindly copied the check from https://github.com/serverless-tencent/serverless-tencent-tools/blob/3c1cabbdb21c0b3ba37248b9c2f609ec552bf8fc/sdk/others/isInChina.js#L12
Still it appears it's faulty. This patch fixes it (I've also proposed a patch for `serverless-tencent-tools`: https://github.com/serverless-tencent/serverless-tencent-tools/pull/6)

Fix IS_IN_CHINA resolution

---

package.json
src/utils/download.js

Sometimes, users can not access to `https://registry.npmjs.org` directly, so they add global proxies for it. But  `got` lib (`package-json` depends on it) don't respect it, so they will get a `ECONNREFUSED` error. Refer to this issue https://github.com/sindresorhus/got/issues/560, so we need [global-tunnel-ng](https://github.com/np-maintain/global-tunnel).

fix: respect global proxy

---

src/cli/utils.js

This is the [updated version of this PR](https://github.com/serverless-components/aws-lambda/pull/26), to work with the new GA components.
The glob `'**'` would not match files such as `[...file].js`. This is critical for the NextJS component to utilize a catch-all API route, and breaks all deployments that try to use them.
Included files before PR:
```
.file.js
[file].js
file.js
```
Included files after PR:
```
.file.js
[...file].js
[file].js
file.js
```

Fix files being omitted

---

src/cli/commands/utils.js
src/cli/index.js
src/cli/utils.js

When working on Tencent commands, we've approached some issues, and after investigation it appeared that it's caused by fact of environment variables not being resolved from `.env` files
Ideally `.env` files should be resolved at earliest stage of a program, and further logic should simply refer to `process.env` for environment variables values.
This PR ensures it's the case.
As there's no test suite, I've tested manually by running few component commands. All worked without issues.

Fix process.env resolution

---

package.json
src/cli/commands-cn/create.js
src/cli/commands-cn/dev.js
src/cli/commands-cn/index.js
src/cli/commands-cn/info.js
src/cli/commands-cn/registry.js
src/cli/commands-cn/run.js
src/cli/commands-cn/utils.js
src/cli/commands/utils.js
src/cli/index.js
src/cli/utils.js

Add commands to support Tencent/Chinese users. It includes:
- add reference of `@serverless/tencent-platform-client`
- update IS_IN_CHINA flag, so if the user manually set `process.env.SERVERLESS_PLATFORM_VENDOR === 'aws'` we won't treat them as China user, or if the user manually set `process.env.SERVERLESS_PLATFORM_VENDOR === 'tencent'` we'll treat them as China user regardless the zimezone
- based on IS_IN_CHINA flag, dynamically require different command set
- add command sets for China/Tencent user

add commands to support China/Tencent user

---

src/cli/commands/run.js

`serverless.yml` `inputs` property was only meant for the `deploy` action, not `remove` or any custom actions.  `inputs` actions other than deploy need to be handled separately, via a method we have not yet considered.
This fixes the first problem and prevents `inputs` from being automatically submit for custom actions and especially `remove` actions, which users currently use more within the CLI.
cc @hkbarton

ensure serverless.yml inputs are for "deploy" only

---

src/cli/utils.js

Fix the bug that we swallowed exception of parsing incorrect YAML format, and throw some other unrelated exception later down the logic.

fix: don't swallow exception of incorrect yaml format

---

src/cli/commands-cn/run.js

fix some drift between commands and commands-cn:
1. only use inputs for `deploy` command
2. use sync for other commands and print outputs immediately

fix some drift between commands and commands-cn

---

README.md
src/cli/index.js

When using `deploy --all` you can deploy everything together.  However, immediately after that, you will want to deploy things separately, to provision updates without risking the application as a whole.  The problem you may run into then is that your `.env` file is only in the parent directory, and you will need to copy it to every subfolder. 
This change enables looking 1 folder up for a `.env` file when deploying a specific component, which is helpful in the use-case above.
* Put a `.env` file in a parent directory, above a component instance you wish to deploy.
* Deploy the component instance in the child directory.

enable putting .env files in the parent directory

---

package.json
src/cli/commands-cn/run.js
src/cli/commands-cn/runAll.js
src/cli/commands-cn/utils.js
src/cli/commands/utils.js
src/cli/utils.js

This change allows reference variables in `.env` at the top level of `serverless.yml`, before referencing variables is only allowed in the `inputs` section.

fix: should allow reference variables in env file at app level

---

src/cli/utils.js
src/legacy.js

- Optimize templates resolution to stop investigation of further directories as soon as answer is known
- Ensure to ignore any crashes in components template resolution (Fixes #623)
- Ignore any dirs starting with `.git`, so far if multicomponent project was a git repository, check assumed it's not a multicomponents project
- Ensure to check for multicomponent project only in applicable scenarios (checking it upfront in all cases was not efficient).
Tested locally

Fix and improve multi component projects detection

---

src/cli/commands/dev.js
src/cli/commands/utils.js
src/cli/utils.js

Memoizing was getting in the way of reloading the yaml file with the same args on file change.

Fix reloading yaml file in dev mode

---

src/cli/commands/dev.js

When running in dev mode and a build is specified in the yaml file, changes trigger double deployments. The first is the actual change you made in `src` and the second is the `dist` change automatically made by the builder.
This PR ignores the specified dist because changes in src trigger a build & deployments.

Ignore watching the dist folder

---

src/cli/commands/utils.js

I've tried a deployment on basic component service, and was faced with following error:
```
% sls --debug
Initializing...
TypeError: Cannot read property 'aws_access_key_id' of undefined
at loadAwsCredentials (/Users/medikoo/npm-packages/@serverless/components/src/cli/commands/utils.js:98:47)
at loadInstanceCredentials (/Users/medikoo/npm-packages/@serverless/components/src/cli/commands/utils.js:111:3)
at loadVendorInstanceConfig (/Users/medikoo/npm-packages/@serverless/components/src/cli/commands/utils.js:207:11)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at Object.module.exports [as run] (/Users/medikoo/npm-packages/@serverless/components/src/cli/commands/run.js:32:24)
at Object.module.exports (/Users/medikoo/npm-packages/@serverless/components/src/cli/index.js:1 …
```

Fix AWS default profile handling

---

src/cli/CLI.js

Introducing hard `process.exit`'s does not allow background tasks to end normally, also may hide async setup issues (e.g. incorrectly setup orphaned async flows, or unhandled rejections).
Additionally it prevents to use project programmatically, as e.g. here: https://github.com/serverlessinc/platform-cn/blob/75836c9628d9b27d8a7ca9487100a31abf3407c8/sp-metrics/code/.scripts/deploy.js#L81 (`finally` has no chance for being executed).
(it was also reported for Components v1 at https://github.com/serverless/cli/issues/9 )
This patch ensures that CLI process ends naturally.

Fix process exit logic

---

package.json
src/cli/index.js
src/cli/notifications/generate-payload.js
src/cli/notifications/request.js

Brings support for backend notifications in Components v2 (as outlined in https://github.com/serverless/roadmap/issues/321)

Support backend notifications

---

src/cli/CLI.js
src/cli/commands-cn/dev.js
src/cli/commands/dev.js

With `SIGINT` case is that if there are no event handlers attached to it, Node.js by default exits process (as if `process.exit()` would be run in a middle of a logic).
If there are `SIGINT` event handlers attached, Node.js leaves exiting to us. In this scenario it seems right to invoke `process.exit()` in a handler, as it's the only way to stop e.g. stop ongoing HTTP requests (and we've received a clear intent from user to stop any ongoing operations).
~~I've also changed `.on` to `.once`, so if Ctrl-C press is doubled we do not produce duplicate close logs~~

Fix handling of SIGINT signal

---

src/cli/CLI.js

/cc @hkbarton 
e.g. in `dev` mode we redeploy original version before we exit

Ensure to support async close handlers on SIGINT

---

src/cli/commands-cn/run.js
src/cli/commands-cn/runAll.js
src/cli/commands/run.js
src/cli/commands/runAll.js
src/cli/index.js
src/cli/notifications/generate-payload.js
src/cli/notifications/print-notification.js

Initial notifications payload generator didn't took into account case where deploy multiple components.
Deployment then was crashing with:
```
% sls deploy --all
(node:11248) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'component' of null
at module.exports (/Users/medikoo/npm-packages/@serverless/components/src/cli/notifications/generate-payload.js:9:33)
at Object.module.exports (/Users/medikoo/npm-packages/@serverless/components/src/cli/index.js:112:25)
at Object.<anonymous> (/Users/medikoo/npm-packages/serverless/bin/serverless.js:35:18)
at Module._compile (internal/modules/cjs/loader.js:1200:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
at Module.load (internal/modules/cjs/loader.js:1049:32)
at Function.Module._load …
```

Ensure support for templates in notifications

---

src/cli/commands/init/index.js
src/cli/commands/init/unpacker.js

Modify recursive call to accept isTopLevel to ignore serverless.yml check before recursing
Modifies recursive call to ignore a missing serverless.yml for the top-level use case.
- Run `sls init fullstack-app`
- note that node modules successfully installed

Support removal of serverless.yml file at top of template

---

src/legacy.js

Previously I've only allowed the deploy command for nested templates, but that was short-sighted. We also need to allow for removal.
The purpose of this whole command restriction is to save up on extensive FS operation caused by checking the child directories on **every framework v1 command**, a valid concern raised by @medikoo

Allow remove command for nested templates

---

package.json

Bumps platform-client so that `sls login` points to `app.serverless.com`

Bump dep to v1.0.6 to redirect login to app.serverless.com

---

src/cli/commands/help.js
src/cli/commands/index.js
src/cli/index.js
src/legacy.js

If you run `serverless help` or `serverless --help` or `serverless -h` in a components context, you'll see the following:

Adds a simple help screen

---

src/cli/commands/help.js

Add a very small tweak to the help syntax in order to distinguish flags from options in the help copy.

Adding option values to help

---

README.md
src/cli/commands/help.js
src/cli/commands/init/index.js

Allow --dir and -d to specify destination directory

---

src/cli/commands-cn/info.js

add source code download URL when you run `sls info`

chore: add source code download url into sls info command for CN

---

package.json
src/cli/commands-cn/index.js
src/cli/commands-cn/init.js
src/cli/index.js
src/cli/interactive-onboarding/cn.js

1. Get data from registry api
2. Users can search for templates by entering name of template
3. Same behavior with `sls init` after choosing a template
Closes https://github.com/serverless/roadmap-tencent/issues/481
- Run the local `bin` binary in a non-serverless project 
- Select templates from list
- Input project name
- User can deploy project immediately after creating it successfully

feat: Add templates to CLI onboarding

---

src/cli/index.js

Fixes a bug introduced in #735 where `sls publish` was broken
- Pull this branch, run `sls publish`
- `sls registry` still shows the registry items
- `sls registry publish` still publishes

Fix regression where sls publish is broken

---

src/cli/commands/help.js

fixes typo in the cli command help

fix: fix typo in the cli command help

---

package.json
src/cli/commands/utils.js

Skip getting default org when dashboard object is not found (ie. logged out)

---

src/cli/commands/info.js

One thing that I have run into, which was really hard to figure out was - `Which version of the express component am I running?!`.
We tell people in the readme that we `HIGHLY recommend pinning this to a specific version`, but users don’t even know what version they use, how to upgrade, or why/when.
I realized this when I ran `sls info` and `sls info --debug` and never saw any of this information. It’s not in the state (which is dumped with `debug`).
This PR addresses that. It looks like this:

Add component name and version to sls info

---

src/cli/commands/login.js

loading config file and passing component name/version is no longer needed by the sdk/dashboard.

update login url by not passing component name/version

---

.github/workflows/validate.yml

Address configuration issue exposed here: https://github.com/serverless/components/runs/1008182875?check_suite_focus=true
PR derives from older master state and due to lack of depth no common ground between PR branch and master is found.

CI: Prevent "no merge base" error

---

src/cli/commands/dev.js

Not sure if it was intentionally left out, I noticed that any `console.info()` statements when in dev mode were not being intercepted. I've added support for it in the layer via serverlessinc/platform#76. This PR prints those intercepted log events out on to the user's console.
- Deploy a component instance with `console.info()` statements
- Start dev mode
- Invoke instance
- Ensure that `console.info()` statements are intercepted and printed out in dev console
- ~[ ] Write / update documentation~

Support console.info() in dev mode

---

.github/workflows/publish.yml
.github/workflows/validate.yml
package.json

Auto publication of release notes was supposed to work since https://github.com/serverless/components/pull/740 was merged, but it wasn't due:
- Bug on `npx` side, due to which unexpected binary was invoked, reported at https://github.com/serverless/components/pull/740 (and that also prevented exposure of below issue)
- Lack of `repository` field on `package.json`
- Ensure to have `github-release-from-cc-changelog` locally installed in _publish_ CI job (prior publication of release notes) That's a workaround for `npx` bug
- Add `repository` field to `package.json`
- Upgraded cache configuration to `actions/cache@v2 (and fixed discovered caching configuration issue)

CI: Fix auto publication of release notes

---

src/cli/commands/dev.js

The Platform now emits 2 new events `instance.action.succeeded` and `instance.action.failed` to simplify things, instead of `instance.deployment...` and `instance.removal....`.
This broken `dev` mode as it was waiting for the `instance.deployment.succeeded` event which has now been deprecated, to show outputs in the CLI after each deployment during `dev` mode.
This fixes that, but also does it by not relying on websockets events to show the message, and instead relies on the response from the `sdk.deploy()` method to log outputs.  Users will see no difference in the experience as a result, but they will have to upgrade.
- Run dev mode and do a deploy via the watcher by saving.

Fix dev mode deployment outputs

---

README.md
package.json
src/cli/commands/utils.js
src/cli/utils.js

**Allow usage of symbolic link for AWS credentials and other files.**
For additional security, using Linux, is a good practice to link files with sensitive content (like credentials) into [Encrypted Private Directory](https://help.ubuntu.com/community/EncryptedPrivateDirectory). These changes allow to use this configurations without fail `fileExistsSync()` check.
**Add [aws-sdk](https://www.npmjs.com/package/aws-sdk) package as dependency**
This is required in order to [assume a role](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) using AWS STS client.
**Makes `loadInstanceCredentials()` asynchronous**
If I have not misunderstood the `loadInstanceCredentials()` function is always called with await operator even though the function was not declared as async. These …

Add support for AWS profile with role_arn configuration

---

src/cli/commands/init/unpacker.js
src/cli/serverlessFile.js
src/cli/utils.js

- Creates yaml file in the root of nested templates on init
- Adds app, org & stage properties to the root yaml
- Removes app, org & stage properties from nested components
- Supports inheriting stage and org properties from root yaml

Creates YAML file in the root of nested templates on init

---

src/cli/CLI.js

Fix process error status code when a session is closed due to an error. 
- Run a deploy command that results in an error
- Run `echo $?` and validate that the result is `1`

Set error status code when sessionStop reason = error

---

src/cli/commands/dev.js
src/cli/commands/run.js
src/cli/commands/runAll.js

Closes #812
- Run `sls deploy`, `sls dev`, or other commands with an organization that does not exist
There may be a better way to do this, and I'm totally open to suggestions - but I believe our websockets implementation only provides a string error.
Alternatively we could refactor the SDK to throw errors with status codes, and then inspect them here.

Catch a 401 on the backend and handle the error on the CLI

---

src/cli/commands-cn/runAll.js

Add success, failure count message for `runAll`
- https://github.com/serverless/roadmap-tencent/issues/543
- https://github.com/serverless/roadmap-tencent/issues/492
- https://github.com/serverless/roadmap-tencent/issues/541

add detailed success/failure message for `runAll`

---

README.cn.md
package.json
src/cli/commands-cn/registry.js
src/cli/commands-cn/runAll.js
src/cli/commands/registry.js
src/cli/utils.js

- Support publishing templates using `serverless.template.yml`
- Ignore `serverless.template.yml`
- Backward compatibility (support publishing template using `serverless.yml`)
- Update Chinese README
- Test in China
https://github.com/serverless/roadmap-tencent/issues/569

Add support for serverless.template.yml

---

CHANGELOG.md
package.json
src/cli/commands-cn/dev.js
src/cli/commands-cn/info.js
src/cli/commands-cn/init.js
src/cli/commands-cn/param.js
src/cli/commands-cn/registry.js
src/cli/commands-cn/run.js
src/cli/commands-cn/runAll.js
src/cli/interactive-onboarding/cn.js

We need to use `traceId` to track the request for `apigw`, we create it in client
Closes #XXXXX
- Run X
- ...

feat: Add traceId field when request apigw

---

CHANGELOG.md
package.json
src/cli/commands-cn/utils.js

`src` will be added `absolute path`, I add another field to save the original path(src and dist), so we can show the current info on website:

feat: add origin src to inputs

---

CHANGELOG.md
package.json
src/cli/commands/runAll.js
src/cli/commands/utils.js
src/cli/index.js
src/cli/serverlessFile.js
src/cli/utils.js

- Remove `app` property requirement from `sls publish` (because the app is determined on `init`)
- Remove `name` and `stage` properties from root level `serverless.yml`
- Remove inputs from the yaml file when running `serverless remove`
- Remove support for single command deploys.

Minor fixes for publish, init and deploy

---

src/cli/commands-cn/run.js

When user run `sls deploy --target subFolder` in a folder, if there's no `serverless.yml` but a `package.json` file in the current folder. This command will try to auto-generate a serverless.yml. Which is not right.

Don't auto generate serverless.yml when sls deploy --target

---

src/cli/commands-cn/utils.js

Closes https://github.com/serverless/roadmap-tencent/issues/630
- create a simple eggjs project: 
- `npm init egg`
- `npm i`
- in the egg project, run
- `path/to/components/bin/bin deploy` should auto generate `serverless.yml` and deploy the code

auto generate serverless.yml for eggjs project

---

CHANGELOG.md
package.json
src/cli/commands/dev.js
src/cli/utils.js

Closes #871 
Fixes a bug where dev mode does not watch parent directories.
Run dev mode on an instance with a src input pointing to a parent directory:
```yml
component: express
name: my-app
inputs:
src: ../src
```
Then make changes to the src files. Without this PR changes, a redeploy will not be triggered. With this PR changes, a redeploy will be triggered.

BUG FIX - dev mode does not watch parent directories

---

CHANGELOG.md
package.json
src/cli/commands/login.js
src/cli/commands/logout.js
src/cli/commands/utils.js

Addresses parts of: https://github.com/serverless/enterprise-plugin/issues/464
- replace `writeConfigFile` and `readConfigFile` + config-related logic with `configUtils` equivalents
- replace `platform-sdk`'s `listTenants` with `listOrgs`
- replace `platform-sdk`'s `refreshToken` with `utils` version of `refreshToken`
- remove dead code `getOrCreateAccessKey` - I've search for that in all projects in `serverless` and `serverlessinc` orgs and I didn't find anything that uses it
To make the review process easier, I've implemented all self-contained changes as separate commits. Unfortunatelly, there are not automated tests, so everything was verified by hand by running `login`, `logout`, `deploy` and `publish/unpublish` commands. 
In order to verify, I've run the following commands:
- Run …

refactor: Use `utils` instead of `platform-sdk` in `login`

---

README.cn.md

update anchor link for `Serverless.yml 介绍`, current link cannot be redirected.

Fix anchor link

---

src/cli/index.js

Closes https://github.com/serverless/roadmap-tencent/issues/787
Currently, the `dotenv` can not remove **# inline comment** in the env file: https://github.com/motdotla/dotenv/issues/484, which will cause error when users use inline comments. This PR will check this situation and throw an message.
**Question**: Is it possible that the value in the `env file` itself contains the # symbol?

fix: check invalid inline comments in env file

---

package.json
src/cli/commands/login.js

Removes dependency on `urls` as passing `loginBrokerUrl` explicitly to `platform-client`'s login is no longer needed. In turn, that allows us to drop `@serverless/platform-sdk` altogether.'
I tested it locally with `login` and `logout` commands.
- Manually login & logout

chore: Drop `@serverless/platform-sdk` dependency

---

CHANGELOG.md
package.json

- Show warning messgae for inline comments in the `dotenv` file: https://github.com/serverless/components/pull/898
- Fix the bug which can't request new login permission without a `dotenv` file: https://github.com/serverless/components/pull/899

release: 3.7.2 version

---

package.json
src/cli/commands-cn/dev.js

Closes https://github.com/serverless/roadmap-tencent/issues/795
- Run X
- ...

fix: Do not try to close debug mode for non-nodejs runtime project

---

package.json

[This bug](https://github.com/cthackers/adm-zip/issues/342) in adm-zip is fixed in v0.5.x
We need to update adm-zip version to close: #872

fix permission lost issue when `sls init`

---

package.json
src/cli/commands/login.js

Use `user_uid` if available as `userId` persisted in local `.serverlessrc` file
Related Asana ticket: https://app.asana.com/0/1200011721510709/1200049124629396
Manually test login/logout

feat: Store `user_uid` as `userId` in local config

---

src/cli/commands-cn/init.js

> issue: https://app.asana.com/0/1200011502754281/1200078207478206
This PR helps to reserve the comments in the serverless.yml of templates
`sls init eggjs-starter`

reserve comments for templates

---

src/cli/commands-cn/init.js

Closes https://github.com/serverless/roadmap-tencent/issues/756
When init a project in CLI, it will automatically add a random uuidv4 value for `appName` field in config yaml.

feat: add random value for appName field when init a project

---

src/cli/CLI.js

https://app.asana.com/0/1200011502754281/1200168199767450
Previously
After

Display complete outputs

---

package.json
src/cli/commands-cn/invoke/index.js
src/cli/commands-cn/invoke/invoke-local/index.js

https://github.com/serverless/components/pull/948#issuecomment-845635059
`jsome` looks to be abandoned, and uses a vulnerable version of `yargs` (which is also not required in this context, since it's not being used as a cli).
This replaces `jsome` with Node's native `util.inspect` function, which should provide the same approximate functionality.
- Run `npm i`
- Check the output for `found 0 vulnerabilities` 🎉

fix: replace `jsome` with `util.inspect`

---

src/legacy.js

When running `help command` within a template project, should print help info from help of components.

Fix: fix help info for template

---

src/cli/commands-cn/invoke/invoke-local/index.js
src/cli/commands-cn/invoke/invoke-local/runPython.js
src/cli/commands-cn/invoke/invoke-local/utils.js

1. 添加 **utf8** 编码格式，防止乱码
2. 允许用户指定 使用哪一个python

fix invoke lcoal for python runtime

---

src/cli/commands-cn/help.js
src/cli/commands-cn/invoke/index.js
src/cli/commands-cn/logs.js
src/cli/commands-cn/utils.js

For the newly added [`multi-scf`](https://github.com/serverless-components/tencent-multi-scf) component, we need to enable the following commands
Related tickets: 
- https://app.asana.com/0/1200011502754281/1200394700504537
- https://app.asana.com/0/1200011502754281/1200394700504540
- https://app.asana.com/0/1200011502754281/1200394700504545

--function param for invoke/logs command

---

src/cli/interactive-onboarding/cn.js

Currently, the `multi-scf-nodejs` template will be ignored when users try to init templates interactively with `sls` command. This PR fixed the issue.
Related: https://app.asana.com/0/1200011502754281/1200515545968615

Enable multi-scf templates

---

src/cli/commands-cn/run.js
src/cli/commands-cn/runAll.js

Add appid cache in client_uid-credentials only when deployment completed, no matter deployment succ or fail

fix: CLI metrics analytics data collection

---

src/cli/commands-cn/help.js
src/cli/commands-cn/invoke/index.js
src/cli/commands-cn/invoke/invoke-local/index.js
src/cli/commands-cn/logs.js

https://app.asana.com/0/1200011502754281/1200578828969029

Add --target support for 3 commands in template dir

---

src/cli/commands-cn/invoke/index.js
src/cli/commands-cn/logs.js

Related ticket
- https://app.asana.com/0/1200011502754281/1200601499823399

Ignore timeout issue when polling logs

---

src/cli/commands-cn/dev.js
src/cli/commands-cn/help.js
src/cli/commands-cn/utils.js
src/legacy.js

Close: https://app.asana.com/0/1200011502754281/1200595402967504/f
---
1. [x] If Chinese user is in component or template project, we just use components logic. @medikoo  I think the change in `legacy.js` will not affect global code, but please take a loot
2. [x] Add **--target** option for `dev` command
3. [x] Check **path** validation

Improve component logic

---

src/cli/commands-cn/invoke/index.js
src/cli/commands-cn/invoke/invoke-local/index.js
src/cli/commands-cn/utils.js

When users execute `sls invoke` or `sls invoke local` in a template folder, try to detect `scf`/`multi-scf` instance directory.
https://app.asana.com/0/1200011502754281/1200578828969029

Detect invoking dir for templates

---

src/cli/commands-cn/telemtry/generatePayload.js
src/cli/commands-cn/utils.js

To add `ciName` and `command` info when creating and saving clientUid on machine and DB, it helps us to debug error

feat: Add more useful info on clientUid

---

src/cli/utils.js
src/legacy.js

1. Add `credentials` command in the template project
2. Fix `=` sign in inputs value

fix `=` sign  for inputs value

---

src/cli/commands-cn/dev.js

We do not need to init a `debug` before we want to close debug mode due to this [PR](https://github.com/serverlessinc/platform-cn/pull/213)
Closes https://app.asana.com/0/0/1200995050585991/f
- Run X
- ...

remove extra debugStart initialization

---

src/cli/commands/run.js

In some complex workflows, like for example, using the website component to automatically deploy a website on PR opening, we want to be able to cleanup completely on PR close and clean all resources. To do this, the cloudfront distributions need to be disabled and then deleted. It takes a variable amount of time from 2-15 minutes. But since component's CLI is not passing through the upstream option _timeout_ there is no way to configure it and it defaults to 60000 ms.
In order to overcome that I've added to the runner the option to read the command option _timeout_ and pass it through.
I could help with the documentation, but I think it is pretty outdated in the src/cli/commands/help.js
Closes #959
- Run _deploy_ or _remove_ command with the option _timeout_ as a value in ms from a …

Add timeout option from serverless command config
