- .travis.yml
Adds the necessary ENV values to the .travis.yml file for being able to publish to npm.
> Add env values to travis

- tests/integration/await-child-components.test.js
- tests/integration/programmatic-usage.test.js
- tests/integration/simple.test.js
Increase all the timeouts to avoid build failures.
Nothing to do here (other than looking at the code)...
> Increase integration test timeouts

- package-lock.json
- package.json
> Bump version to 0.1.1

- .gitignore
- registry/aws-lambda/index.js
- registry/aws-lambda/index.test.js
Includes a small bug fix that handles removals when no deployment happened
> Added Lambda Tests (Includes small bug fix)

- registry/aws-dynamodb/index.js
Fixes the race conditions introduced due to callback misuse. Wrapped the callbacks into Promises.
Use the following test service:
```yml
components:
myDynamoDBTable:
type: aws-dynamodb
inputs:
region: us-east-1
tables:
- name: my-table-${self.serviceId}
hashKey: id
indexes:
- name: MyIndex
type: global
hashKey: id
schema:
id: number
firstName: string
lastName: string
options:
timestamps: true
```
Replace the `module.exports` part in [`registry/aws-dynamodb/index.js`](https://github.com/serverless/serverless-components/blob/0c79d42b4d314d77675ee053c5acc1a878e4a777/registry/aws-dynamodb/index.js#L319-L325) with the following code snippet:
```js
module.exports = {
deploy,
remove,
insert,
destroy,
get,
async test(inputs, context) {
const tablename = …
```
> Fix DynamoDB component helper race conditions

- .gitignore
- examples/retail-app/README.md
Adds a simple getting started to the retail app
> Add getting started section to retail-app

- package-lock.json
- registry/aws-iam-role/index.js
- registry/aws-iam-role/index.test.js
- registry/aws-s3-bucket/index.js
- registry/aws-s3-bucket/index.test.js
- src/utils/components/generateContext.js
- src/utils/telemetry/track.js
Includes a bug fix where no updates happen when the bucket name changes
> Added S3 Tests (Includes a bug fix)

- src/utils/components/executeComponent.js
- src/utils/components/getComponentsToRemove.js
- src/utils/components/getComponentsToRemove.test.js
Closes https://serverlessteam.atlassian.net/browse/SC-203
https://serverlessteam.atlassian.net/browse/SC-203
> WIP null check for promise

- registry/aws-lambda/index.js
- registry/aws-lambda/index.test.js
Add idempotency to AWS Lambda component.
Deploy the `basic` example. Copy the state and save it to a temp file. Remove the `basic` example. Replace its state with the previously copy-and-pasted state information. Remove again. The AWS Lambda component shouldn't throw an error.
> Add idempotency to AWS Lambda remove function

- examples/retail-app/README.md
Updated the preview link
* Run X
* ...
> Update preview link

- examples/circular-dependencies/README.md
- examples/circular-dependencies/serverless.yml
- examples/file-system-components/README.md
- examples/file-system-components/my-function/index.js
- examples/file-system-components/my-function/serverless.yml
- examples/file-system-components/serverless.yml
- examples/signal-handling/README.md
- examples/signal-handling/my-slow-function/index.js
- examples/signal-handling/my-slow-function/serverless.yml
- examples/signal-handling/serverless.yml
This PR adds examples to showcase recently added core features.
Follow the `README` file and run `deploy` and `remove` in the corresponding example directory.
> Add examples to showcase new core features

- .editorconfig
Just added some minor tweaks to streamline the development flow.
Closes SC-243
> Some minor EditorConfig tweaks

- .appveyor.yml
- package.json
- src/utils/components/getComponentFunctions.js
- src/utils/components/getComponentFunctions.test.js
- tests/integration/await-child-components.test.js
- tests/integration/programmatic-usage.test.js
- tests/integration/simple.test.js
Fixes the issues we're currently having with AppVeyor.
~**NOTE:** I updated everything so that it runs on Windows. It looks like Appveyor is super slow ATM causing our integration tests to timeout. I raised the timeout-limit to 60 seconds w/o success. Maybe we should disable integration tests on Appveyor 🤔~
Take a look into the AppVeyor build logs.
> Fix AppVeyor setup

- examples/basic/serverless.yml
- examples/blog/serverless.yml
- examples/circular-dependencies/serverless.yml
- examples/file-system-components/serverless.yml
- examples/github-webhook-example/serverless.yml
- examples/landing-page/serverless.yml
- examples/netlify-site-example/serverless.yml
- examples/restapi/serverless.yml
- examples/retail-app/serverless.yml
- examples/s3-uploader-downloader/serverless.yml
- examples/signal-handling/serverless.yml
- package-lock.json
- package.json
- registry/tests-core-version-compatibility/index.js
- registry/tests-core-version-compatibility/serverless.yml
- src/run.js
- src/utils/components/getComponent.js
- src/utils/components/getComponent.test.js
- src/utils/components/index.js
- src/utils/components/packageComponent.js
- src/utils/components/packageComponent.test.js
- src/utils/index.js
- src/utils/pack.js
- src/utils/pack.test.js
- src/utils/validateCoreVersion.js
- src/utils/validateCoreVersion.test.js
From within the basic example directory, run the following:
```
components package --path ./
```
```
components package --path ./ --format tar
```
> Added package command and core version validation

- registry/static-website/serverless.yml
Closes #170 
* Run `components deploy`
* Verify that a CloudFront distribution is created
* Verify that a Route53 mapping is created
* Verify that the site is accessible via the CloudFront domain e.g. xxxxxxxxxxx.cloudfront.net
* Verify that the site is accessible via the S3 site url
> Uncomment cloudfront and route53 component config.

- CONTRIBUTING.md
- DEVELOPMENT.md
This PR adds a DEVELOPMENT.md which provides instructions on how to do basic development on this project.
> Add DEVELOPMENT.md

- Dockerfile
Updates Node.js in the Dockerfile to the latest version.
> Update Node.js version in Dockerfile

- examples/basic/serverless.yml
- package-lock.json
- package.json
- src/utils/components/downloadComponent.js
- src/utils/components/downloadComponent.test.js
- src/utils/components/generateContext.js
- src/utils/components/getComponentFromUrl.js
- src/utils/components/getComponentFromUrl.test.js
- src/utils/components/getComponentRootPath.js
- src/utils/components/getComponentRootPath.test.js
- src/utils/components/getComponentRootPathFromUrl.js
- src/utils/components/getComponentRootPathFromUrl.test.js
- src/utils/components/getComponentsBucketRoot.js
- src/utils/components/getComponentsCachePath.js
- src/utils/components/getComponentsCachePath.test.js
- src/utils/components/getComponentsFromServerlessFile.js
- src/utils/components/index.js
create & deploy the following component:
```yml
version: 0.0.1
components:
downloadedComponent:
type: https://github.com/eahefnawy/component-url-test/archive/master.zip
inputs:
test: abc
```
- You should see a message stating the component is downloading, then it will run its nested components (IAM and Lambda).
- Try deploying again, the component will be used from the cache and won't be downloaded again.
> Download Component from URL

- .npmignore
This PR adds a number of files to npmignore that are not needed by the npm package.
> Update npmignore to exclude unneeded files

- registry/s3-dirloader/package-lock.json
This PR fixes some unresolved merge conflicts in [s3-dirloader/package-lock.json](https://github.com/serverless/components/blob/master/registry/s3-dirloader/package-lock.json). I removed the package-lock.json that was broken and created a new one.
* Run X
* ...
> Fix unresolved merge conflicts

- README.md
Update Slack invite link and meetups link
* Run X
* ...
> Update Slack invite link and meetups link

- registry/netlify-site/src/index.js
This PR removes obsolete state existence check from netlify-site component and adds a check which verifies that required API tokens are defined.
* Run `components remove` without netlify token defined. It should display message "Failed to remove netlify site..." and leave netlify-site state object to state.json and continue removing other components.
* Run `components remove` without github token defined. It should display message "Failed to remove netlify site..." and leave netlify-site state object to state.json and continue removing other components.
> Remove obsolete state checking from netlify-site component

- registry/aws-lambda-secure/.gitignore
- registry/aws-lambda-secure/examples/basic/handler.js
- registry/aws-lambda-secure/examples/basic/serverless.yml
- registry/aws-lambda-secure/index.js
- registry/aws-lambda-secure/package-lock.json
- registry/aws-lambda-secure/package.json
- registry/aws-lambda-secure/serverless.yml
Adding a new Component to the Registry
> adding new aws-lambda-secure component to registry

- Dockerfile
- dbuild
- dexec
- docker-compose.yml
This is a simple one. We update the Docker setup to reflect recent changes (e.g. added some convenience scripts which make it possible to `exec` to a container started via `docker-compose up`).
> Update Docker setup

- src/utils/misc/handleSignalEvents.js
> Fix typo in handleSignalEvents

- README.md
Just added the missing links in the `README.md`...
> Add missing SNS component documentation references

- registry/aws-ecs-cluster/README.md
- registry/aws-ecs-cluster/package-lock.json
- registry/aws-ecs-cluster/package.json
- registry/aws-ecs-cluster/serverless.yml
- registry/aws-ecs-cluster/src/index.js
- registry/aws-ecs-cluster/src/index.test.js
Closes #273 
```yaml
components:
myAwsEcsCluster:
type: aws-ecs-cluster
inputs:
clusterName: my-cluster
```
> Adds ECS Cluster component

- registry/twilio-phone-number/README.md
Another doc regeneration to avoid "doc drifting"...
> Re-generate docs

- examples/cloudflare-workers-example/serverless.yml
- registry/cloudflare-workers/README.md
- registry/cloudflare-workers/serverless.yml
- registry/cloudflare-workers/src/index.js
Closes #XXXXX
Deploy workers to your site using the following serverless.yml
```
type: my-application
components:
myCloudflareWorkers:
type: cloudflare-workers
inputs:
accountId: ACCOUNT_ID_HERE
credentials:
authKey: CLOUDFLARE_AUTH_KEY_HERE
authEmail: CLOUDFLARE_AUTH_EMAIL_HERE
zoneId: ZONE_ID_HERE
scriptPath: ./index.js
route: example.com/path/*
```
cc @pinkerton @EverlastingBugstopper @nirvik
> Update Cloudflare Workers component to use credentials from inputs

- src/types/AwsDynamoDB/index.js
- src/types/AwsSnsSubscription/index.js
- src/types/AwsSnsTopic-ISource-ISink/index.js
- src/types/AwsSnsTopic-ISource-ISink/serverless.yml
- src/types/AwsSnsTopic/index.js
- src/types/TwilioApplication/index.js
- src/types/TwilioPhoneNumber/index.js
Update the old Component / Type implementations to use `shouldDeploy`.
Furthermore remove `hydrate` and manual state management.
> Update old Type implementations

- scripts/prepare.js
> npm install fix

- registry/AwsApiGateway/serverless.yml
- registry/AwsApiGateway/src/index.js
- registry/AwsApiGateway/src/index.test.js
- registry/AwsApiGateway/src/utils.js
- registry/AwsSnsSubscription/src/index.js
- registry/AwsSnsSubscription/src/index.test.js
- registry/AwsSnsTopic/src/index.js
- registry/AwsSnsTopic/src/index.test.js
- registry/RestApi/src/index.js
- registry/RestApi/src/index.test.js
- registry/TwilioPhoneNumber/src/index.js
- registry/TwilioPhoneNumber/src/index.test.js
> Add shouldDeploy to components

- registry/AwsSnsSubscription/src/index.js
- registry/AwsSnsSubscription/src/index.test.js
- registry/AwsSnsTopic/src/index.js
- registry/AwsSnsTopic/src/index.test.js
- registry/TwilioApplication/src/index.js
- registry/TwilioApplication/src/index.test.js
- registry/TwilioPhoneNumber/src/index.js
- registry/TwilioPhoneNumber/src/index.test.js
> Add hydrate method to some components

- registry/AwsLambdaCompute/src/index.js
- registry/AwsLambdaFunction/serverless.yml
- registry/AwsLambdaFunction/src/index.js
- registry/AwsLambdaFunction/src/index.test.js
Closes #305 
* Specify the code property as a path to a jar file
* Deploy a serverless component
> fix the issue with a code property as an archive file

- __mocks__/aws-sdk.js
- registry/AwsApiGateway/src/index.js
- registry/AwsApiGateway/src/index.test.js
This is a follow-up PR of https://github.com/serverless/components/pull/344
After searching around I was able to find the following docs which include the error code used in this implementation: https://docs.aws.amazon.com/apigateway/api-reference/handling-errors/
> Add AwsApiGateway remove idempotency

- registry/AwsS3Bucket/serverless.yml
- registry/AwsS3Bucket/src/index.js
- registry/AwsS3Bucket/src/indext.test.js
Adds a regex check which validates the S3 bucket name according to https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html
/cc @sebito91
> AwsS3Bucket name regex validation

- registry/AwsApiGateway/src/index.test.js
- registry/AwsCloudWatchEventsRule/src/index.test.js
- registry/AwsIamPolicy/src/index.test.js
- registry/AwsIamRole/src/index.test.js
- registry/AwsLambdaFunction/src/index.test.js
- registry/AwsProvider/src/index.js
- registry/AwsProvider/src/index.test.js
- registry/AwsS3Bucket/src/indext.test.js
- registry/AwsS3Website/src/index.test.js
- registry/AwsSnsSubscription/src/index.test.js
- registry/AwsSnsTopic/src/index.test.js
This adds a basic validation to check whether the necessary AWS configuration is properly set.
/cc @shortjared
> Add AwsProvider config validation

- .eslintrc.js
- __mocks__/aws-sdk.js
- bin/components
- bin/serverless
- bin/sls
- registry/.eslintrc.js
- registry/AwsLambdaFunction/src/index.test.js
- registry/AwsProvider/src/index.js
- registry/AwsProvider/src/index.test.js
- scripts/doc-gen.js
Adds the getAccountId method to the provider which could be used by components to retrieve the accountId. Also includes some lint fixes.
> Some improvements for AwsProvider

- registry.json
- templates/api/code/index.js
- templates/api/serverless.yml
> add api gateway to registry and example

- README.md
This adds AWS SNS Topic component to the component list. Should wait for https://github.com/serverless-components/aws-sns-topic/pull/1
> Add SNS Topic Component to readme

- README.md
- src/lib/componentDeclarative/utils/getLocalComponentsPaths.js
Fixes local component path reduce and some read me fixes
> Fix local component path reduce

- src/lib/componentDeclarative/serverless.js
Brings back the auto-removal of components (when they're removed from `serverless.yml`).
> Auto component removal

- bin/cli
- package.json
> cli options improvements

- README.md
Quick typo fix in `README.md`!
> readme - quick typo fix

- src/utils/download.js
This PR adds support for local component packages referenced via a valid npm package name or absolute path, as discussed in @serverless/template issue [#6](https://github.com/serverless/template/issues/6).
> Add support for unpublished/local packages.

- templates/tencent-fullstack-application/README_CN.md
HI，I am Tabor, this is Tencent-full-stack-application README for the Chinese version.
> Add  README for chinese version.

- templates/tencent-fullstack-application/README.md
- templates/tencent-fullstack-application/README_CN.md
> README description

- templates/tencent-fullstack-application/README_CN.md
Update Chinese docs to support streamlined sign-up feature.
* Remove configure step
* Add notes about scan QR code
> Update Full-stack Component Chinese docs

- templates/tencent-fullstack-react-application/serverless.yml
- templates/tencent-fullstack-vue-application/package.json
- templates/tencent-fullstack-vue-application/serverless.yml
- templates/tencent-python-rest-api/serverless.yml
See https://github.com/serverless-components/tencent-apigateway/pull/3 for more information.
> Update tencent-fullstack-* examples

- README.md
> Fixing a few typos on Components blog

- templates/tencent-eggjs/README.md
- templates/tencent-eggjs/README_EN.md
- templates/tencent-flask/README.md
- templates/tencent-flask/README_EN.md
- templates/tencent-fullstack-react-application/README.md
- templates/tencent-fullstack-react-application/README_EN.md
- templates/tencent-fullstack-vue-application/README.md
- templates/tencent-fullstack-vue-application/README_EN.md
- templates/tencent-laravel/README.md
- templates/tencent-laravel/README_EN.md
- templates/tencent-python-rest-api/README.md
- templates/tencent-python-rest-api/README_EN.md
Update component v1 template URL 
* [ √ ] Write / update documentation
* [ √] Run Prettier
> Update template url

- README.md
Fix typo; `serverles.yml` -> `serverless.yml`
> Add missing s

- package.json
- src/cli/index.js
- src/cli/interactive-onboarding/cn.js
- src/cli/utils.js
- src/legacy.js
Dedicated interactive CLI onboarding, at this point enabled only for users in China.
Waiting for v2 components to be ready and listed as proposed project starters (cc @tinafangkunding )
> Interactive CLI onboarding

- package.json
- src/cli/commands-cn/dev.js
- src/cli/commands-cn/info.js
- src/cli/commands-cn/registry.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/utils.js
- src/cli/index.js
- src/legacy.js
replace all deps regarding tencent, remove word `tencent`
> update name of platform deps in China

- package.json
- src/cli/commands-cn/utils.js
fix a bug in China commands that not resolving the dist folder, this causes an issue when running deployment outside of the project folder by specifying the deployment target folder.
> fix bug in CN commands of not resolving dist folder

- src/cli/commands/utils.js
Adds Environment variables to integrate the new Components implementation with a Kubernetes cluster (which in turn runs Knative).
Trust me, you don't want to test this end-to-end...
> Knative integration

- src/cli/commands-cn/runAll.js
- src/cli/commands-cn/utils.js
- src/cli/utils.js
fix bugs being found during the testing for CN commands
> fix deploy all for cn-commands

- README.cn.md
Fix typo and Update Dashboard Link
> Fix typo and Update Dashboard Link for Chinese doc

- package.json
- src/cli/index.js
Supporting global http/https proxy if those env variables are given.
> support global http/https proxy setting

- src/cli/commands/utils.js
Resolving conflicts and reopening #613
> Fix dist paths when running --all flag

- README.cn.md
- README.md
Updated documentation to describe the exclude feature.
N/A
N/A
> update doc to describe exclude feature

- src/cli/utils.js
- src/legacy.js
Runs components if running in a directory with templates.
> Run components login in template directory

- src/cli/commands/info.js
- src/cli/commands/run.js
- src/cli/commands/runAll.js
Taking meta logging out of debug mode as requested by @ac360
> Always log meta data

- templates/graphql/resolvers.js
- templates/graphql/schema.graphql
- templates/graphql/serverless.yml
For use with the [GraphQL Component](https://github.com/serverless-components/graphql)
> Add GraphQL template

- src/cli/commands-cn/registry.js
> chore: load featured components through API

- src/cli/commands-cn/run.js
> feat: showing progress/speed when deploy large code folder

- src/cli/commands-cn/info.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/utils.js
> chore: output dashboard url after successful deployment

- README.cn.md
- src/cli/commands-cn/run.js
- src/cli/commands-cn/utils.js
Closes https://github.com/serverless/components/issues/640
> feat: support inputs for custom commands

- src/cli/commands-cn/info.js
- src/cli/interactive-onboarding/cn.js
Fix https://github.com/serverless/components/issues/634
> fix: fix template downloading doesn't work with proxy

- templates/website/package.json
As reported and fixed by @stevewillard
> Fix duplicate plugins build issue for website component

- src/cli/commands/run.js
- src/cli/commands/runAll.js
- src/cli/commands/utils.js
Fixing regression caused by #648 and follow up for #658
Wrapping `run` and `runAll` code in try/catch to be able to disconnect the sdk.
> Fix CLI hanging on error

- src/cli/commands-cn/dev.js
> chore: make dev mode exiting more robust

- src/cli/notifications/print-notification.js
> fix typo in print-notification

- package.json
- src/cli/commands-cn/create.js
- src/cli/commands-cn/registry.js
* Template registry for CN
* backward compatibility for component registry
> feat: support registry template

- src/cli/commands/runAll.js
Without this reordering, we are unable to `getDefaultOrgName()`, which causes `Missing "org" property error`.
The expected behavior is to let the user know they need to be logged in so that we could get their default org name and make the org property optional.
> Make sure user is logged in before runAll

- package.json
- src/cli/commands-cn/registry.js
> fix: should not continue execution if registry package is not found

- package.json
- src/cli/commands-cn/run.js
Fix below error:
Because we have do login here https://github.com/serverless/components/blob/master/src/cli/commands-cn/run.js#L24, so if command is login, do nothing here
> fix: login command error

- README.md
Use javascript so it'll render comments
Closes #XXXXX
- Run X
- ...
> fix readme json

- README.cn.md
Update CN docs to include template registry related documentation.
> chore: update CN docs including template registry docs

- src/cli/commands-cn/init.js
support automatically install npm dependencies for CN init command.
> feat: support auto install npm deps for cn init

- src/cli/serverlessFile.js
- Makes sure org and app props are at the top
- Removes yaml dump, and instead saves files content as a string to preserve comments.
- Fixes the `inputs: null` issue caused by yaml dump
- Removes excessive newlines
> Reorder properties on init

- package.json
> Release 2.32.0

- README.md
Corrects spelling mistakes in the readme
> Correct spelling mistakes

- src/cli/commands/init/utils.js
Simple fix, I forgot an equals sign in the .env template
> Forgot an equals sign

- src/cli/commands/registry.js
- src/cli/utils.js
Otherwise, the Lambda function would return an `internal server error` and it'd be hard to figure out what happened.
> Validate node_modules exists when publishing components

- package.json
- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/commands-cn/utils.js
support `--debug` for CN user.
> feat: support debug mode for CN platform

- package.json
* support `--debug` for CN user
* support `--dir` option for `sls init` (global version)
> Release 2.33.0

- package.json
- src/cli/commands-cn/help.js
- src/cli/commands-cn/index.js
Add `--help` support for CN commands according to https://github.com/serverless/roadmap-tencent/issues/459
> chore: add --help support for CN commands

- package.json
- src/cli/commands-cn/run.js
The SDK recently added the ability to report agent which identity who's using SDK. Report CLI agent here.
> chore: add sdk agent reporting

- src/cli/notifications/generate-payload.js
Follows https://github.com/serverless/serverless/issues/8041
> Expose isStandalone for analytics

- README.cn.md
> chore: update CN doc adding type system related docs

- src/cli/commands/init/unpacker.js
If we're a v1 project, set the service and app name.
> Init: set service and app for v1 projects

- .github/workflows/validate.yml
- src/cli/commands/dev.js
> Pass dev: True to sdk deploy

- CHANGELOG.md
- package.json
> Release 2.43.3

- src/cli/interactive-onboarding/cn.js
User can select language scf demo
- Run X
- ...
> feat: Add support language selecting for scf-demo

- src/cli/commands/init/unpacker.js
Passes the newly created directory instead of relying on process.cwd()
> Pass the actual directory, instead of process.cwd

- src/cli/commands-cn/init.js
Closes https://github.com/serverless/components/issues/769
- Run X
- ...
> fix: polyfill for fs.promises

- src/cli/interactive-onboarding/cn.js
> feat: add default limitation for onboarding select

- src/cli/commands-cn/init.js
- src/cli/commands-cn/utils.js
- src/cli/interactive-onboarding/cn.js
Closes https://github.com/serverless/roadmap-tencent/issues/519#event-3683538412
- Run X
- ...
> feat: add default project name while process onboarding

- CHANGELOG.md
- package.json
- src/cli/commands-cn/init.js
Release https://github.com/serverless/components/pull/777
- Run X
- ...
> Release for adding default project name in config file

- CHANGELOG.md
- package.json
> Release v2.34.9

- .github/workflows/validate.yml
- CHANGELOG.md
- package.json
- src/cli/commands-cn/init.js
- src/cli/commands/init/utils.js
To be merged prior releasing Framework v2
> v3: Drop support for Node.js versions below v10

- CHANGELOG.md
- package.json
- src/cli/interactive-onboarding/cn.js
> feat: search text on case-insensitive

- CHANGELOG.md
- package.json
- src/cli/commands-cn/init.js
> fix: fix wrong file created when yaml file already existed

- src/cli/commands/utils.js
> throw error when using plugins with components

- README.md
- src/cli/commands-cn/utils.js
- src/cli/commands/run.js
- src/cli/commands/utils.js
- src/cli/utils.js
Supports passing inputs via the CLI according to Option C in the following specs:
https://github.com/serverless/roadmap/issues/453
https://github.com/serverless/roadmap-tencent/issues/512
> Supports passing inputs via the CLI

- CHANGELOG.md
- README.cn.md
- README.md
- package.json
- src/cli/commands-cn/index.js
- src/cli/commands-cn/param.js
Closes https://github.com/serverless/roadmap-tencent/issues/506
- Run X
- ...
> feat: Add parameters set and list on cli

- src/cli/commands/dev.js
This fixes a bug that happens when running `serverless dev` mode and encountering a deployment error (e.g. due to invalid inputs).  Currently, the experience hangs due to a missing `return`.  This fixes that.
This also slightly improves error messages.
- Run `serverless dev` with an invalid input causing a failed deployment.  It should not result in an `Unhandled promise error`.
> fix deployment errors and improve error messages

- CHANGELOG.md
- README.cn.md
- package.json
- src/cli/commands-cn/dev.js
- src/cli/commands-cn/info.js
- src/cli/commands-cn/param.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/utils.js
According this PR: https://github.com/serverless/components/pull/800 and https://github.com/serverless/components/pull/809, we only need to write `commandInputs` and insert it into final config
> fix: parse cli --input args

- src/cli/commands-cn/registry.js
- src/cli/interactive-onboarding/cn.js
- Choose template
- Choose runtime for SCF
> Improve onboarding experience in cli

- CHANGELOG.md
- package.json
- src/cli/commands-cn/registry.js
- src/cli/commands-cn/run.js
> fix: convert dash to undersocre in command

- CHANGELOG.md
- package.json
- src/cli/commands-cn/help.js
- src/cli/commands-cn/run.js
Added `sls bind role` command for users to bind CAM roles
- https://github.com/serverless/roadmap-tencent/issues/596
- https://github.com/serverless/roadmap-tencent/issues/579
> Add a new command for users to init CAM roles using `sls bind role`

- CHANGELOG.md
- package.json
- src/cli/commands-cn/dev.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/commands-cn/utils.js
- src/cli/index.js
- Improve Chinese translation in CLI
- Do not send local credentials to backend
- Run X
- ...
> improve translation

- CHANGELOG.md
- package.json
- src/cli/commands-cn/dev.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/commands-cn/utils.js
- src/cli/index.js
Reverts serverless/components#841
> Revert "improve translation"

- src/cli/CLI.js
- src/cli/commands-cn/info.js
- src/cli/commands-cn/infoAll.js
- src/cli/commands-cn/utils.js
- src/cli/commands/info.js
- src/cli/commands/infoAll.js
- src/legacy.js
Enable `sls info` and `sls info --debug` command for nested templates
https://github.com/serverless/roadmap-tencent/issues/621
> sls info command for nested templates

- src/cli/commands-cn/utils.js
- src/cli/index.js
> update translation and dashboard url

- CHANGELOG.md
- package.json
- Update dashboard URL #846
- Fix `serverless deploy --target` bug #845
- Add `serverless info` support for nested template #842
> Release v3.4.3

- src/cli/commands-cn/dev.js
Closes https://github.com/serverless/roadmap-tencent/issues/594
- Run X
- ...
> feat: improve dev mode

- src/cli/commands-cn/dev.js
Reverts serverless/components#848
> Revert "feat: improve dev mode"

- README.cn.md
- README.md
- src/cli/index.js
> fix: support http_proxy & https_proxy environment variables

- src/cli/CLI.js
This adds language to the notification component users get when first using a component, which summarizes how the implementation works, its security implementations, and where to learn more.
- Log out and try to use a Component via `serverless deploy`
> improve implementation and security communication

- CHANGELOG.md
- README.md
- package.json
> feat: release new China Debug API

- CHANGELOG.md
- package.json
- Auto generate `serverless.yml` when `serverless deploy` for eggjs APP
- Update @serverless/platform-client-china version (support caching feature in China)
> Release v3.5.0

- README.cn.md
> docs: update readme

- src/cli/commands-cn/dev.js
> fix: add orgUid for dev mode

- CHANGELOG.md
- package.json
> Fix dev deploy

- README.md
Removed references for local credentials in the readme, and added references for Providers instead.
> Remove local credentials from Readme

- src/cli/commands-cn/dev.js
- src/cli/commands/dev.js
Closes https://github.com/serverless/roadmap-tencent/issues/758
- Run X
- ...
> close debug mode before start dev

- README.cn.md
Remove org from China Readme File as the `org` is not used in China Platform
[None]
[None]
> remove org

- src/cli/commands-cn/dev.js
> fix: check valid field

- CHANGELOG.md
- package.json
1. [CLI Experience] unsupported command error message. https://github.com/serverless/roadmap-tencent/issues/718 @timqian 
2. [CLI Experience] Force cancel dev mode can't enter dev mode. https://github.com/serverless/roadmap-tencent/issues/758 @zongUMR
> feat: release cli 3.7.1 version

- src/cli/interactive-onboarding/cn.js
Closes https://app.asana.com/0/1200011502754281/1200046739955657/f
- Run X
- ...
> feat: Add keywords and searching for sls onboarding

- src/cli/commands-cn/registry.js
Closes https://app.asana.com/0/1200011502754281/1200046588610092/f
- Run X
- ...
> feat: Add translation and update registry url

- CHANGELOG.md
- package.json
> feat: Release 3.7.4

- CHANGELOG.md
- package.json
- src/cli/commands-cn/dev.js
Closes https://app.asana.com/0/1200011502754281/1200073698180974/f
- Run X
- ...
> fix: runtimeInfo for runtime check

- src/cli/commands-cn/info.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/utils.js
- src/cli/utils.js
Closes https://app.asana.com/0/1200011502754281/1200090410758566/f
1. Add more logic for judging a folder is template or not:
1. All sub folders use same app or stage
2. All sub folders do not have app or stage
2. Hoisting some basic validation before user's login in a valid instance project:
- Check current folder has a yml config.
- Check name and component fields.
> fix: runningTemplate logic and check basic validation.

- src/cli/commands-cn/dev.js
- src/cli/commands-cn/info.js
- src/cli/commands-cn/infoAll.js
- src/cli/commands-cn/registry.js
- src/cli/commands-cn/utils.js
Closes:
1. https://app.asana.com/0/1200011502754281/1200096501801130/f
2. https://app.asana.com/0/1200011502754281/1200096501801146/f
3. https://app.asana.com/0/1200011502754281/1200096501801137/f
> feat: improve cli

- CHANGELOG.md
- package.json
> feat: release 3.8.0

- CHANGELOG.md
- package.json
- src/cli/commands-cn/run.js
> fix: lack field and typo-3.8.1

- src/cli/commands-cn/init.js
- src/cli/commands-cn/run.js
- src/cli/interactive-onboarding/cn.js
- https://app.asana.com/0/1200011502754281/1200096501801115
- https://app.asana.com/0/1200011502754281/1200096501801123
> Better cli logs

- src/cli/commands-cn/dev.js
Fix the dev mode that does not print real-time log in first time.
> fix: dev log print

- src/cli/CLI.js
https://app.asana.com/0/1200011502754281/1200187964367062
> Update help doc link

- src/cli/commands-cn/credentials.js
- src/cli/commands-cn/help.js
- src/cli/commands-cn/index.js
- src/cli/index.js
- src/cli/utils.js
Closes https://app.asana.com/0/1200011502754281/1200046588610090/f
> feat: Login process

- src/cli/commands-cn/dev.js
- src/cli/commands-cn/run.js
https://app.asana.com/0/1200011502754281/1200211330092204
> Translate logs

- CHANGELOG.md
- package.json
> feat: release 3.9.0

- src/cli/commands-cn/credentials.js
- src/cli/commands-cn/dev.js
- src/cli/commands-cn/info.js
- src/cli/commands-cn/param.js
- src/cli/commands-cn/registry.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/commands-cn/utils.js
- src/cli/index.js
- src/cli/utils.js
Closes https://app.asana.com/0/1200011502754281/1200246166175449/f
- Run X
- ...
> feat: update long-term login messages

- CHANGELOG.md
- package.json
> release 3.9.1

- src/cli/commands-cn/credentials.js
- src/cli/commands-cn/help.js
- src/cli/commands-cn/utils.js
- src/cli/utils.js
Closes https://app.asana.com/0/1200011502754281/1200251467401443/f
> fix login message

- CHANGELOG.md
- package.json
> release 3.9.2

- src/cli/commands-cn/invoke/invoke-local/index.js
- src/cli/commands-cn/invoke/invoke-local/utils.js
> Improve invoke local

- src/cli/commands-cn/invoke/index.js
- src/cli/commands-cn/logs.js
For `sls logs`
For `sls invoke`
Known issue:
- Due to this bug on tencent-sdk: https://github.com/serverless-plus/tencent-sdk/issues/6, sometimes new logs might be lost
> Refine sls invoke and sls logs

- src/cli/commands-cn/logs.js
The time info accepted by Tencent CLS must be UTC +8
Ref: https://app.asana.com/0/1200011502754281/1200211330092190
> Convert timezone before formatting time

- package.json
- src/cli/commands-cn/help.js
- src/cli/index.js
Generate help info for a specific command on demand
Ref: https://app.asana.com/0/1200011502754281/1200276428005448
> New help commands

- src/cli/commands-cn/help.js
Ref: https://app.asana.com/0/1200011502754281/1200276428005448
Previously
Now
> Refine --help info

- src/cli/commands-cn/invoke/invoke-local/index.js
- src/cli/commands-cn/invoke/invoke-local/runPython.js
- src/cli/commands-cn/invoke/invoke-local/utils.js
Closes https://app.asana.com/0/1200011502754281/1200376732735304/f
- Run X
- ...
> feat: invoke local for scf python

- src/cli/commands-cn/help.js
- src/cli/commands-cn/invoke/invoke-local/utils.js
Close: https://app.asana.com/0/1200011502754281/1200377032163719/f
> Multi scf support for invoke local

- package.json
- src/cli/commands-cn/dev.js
- src/cli/commands-cn/init.js
- src/cli/commands-cn/invoke/index.js
- src/cli/commands-cn/invoke/invoke-local/index.js
- src/cli/commands-cn/logs.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/commands-cn/telemtry/areDisabled.js
- src/cli/commands-cn/telemtry/cache-path.js
- src/cli/commands-cn/telemtry/generatePayload.js
- src/cli/commands-cn/telemtry/index.js
- src/cli/commands-cn/utils.js
Close: https://app.asana.com/0/1200011502754281/1200521062995970/f
TODO: Add more comments for code
> feat: init the components analytics collect and send

- src/cli/interactive-onboarding/cn.js
Enable users to choose runtime of multi-scf templates
https://app.asana.com/0/1200011502754281/1200515545968615
> Enable multi-scf starter template choices

- CHANGELOG.md
- package.json
- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/interactive-onboarding/cn.js
> fix: remove telemetry function in run

- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/commands-cn/telemtry/generatePayload.js
- src/cli/commands-cn/telemtry/index.js
- src/cli/commands-cn/utils.js
> test telemetry on canary

- src/cli/commands-cn/utils.js
> fix wrong file

- CHANGELOG.md
- package.json
> release 3.13.2

- src/cli/commands-cn/telemtry/generatePayload.js
- src/cli/interactive-onboarding/cn.js
Close: https://app.asana.com/0/0/1200551984502646/f
> Add telemtry data collection for onboarding

- package.json
- src/cli/CLI.js
- src/cli/commands-cn/invoke/index.js
- src/cli/commands-cn/logs.js
- src/cli/commands-cn/utils.js
- src/cli/index.js
Related tickets: 
- https://app.asana.com/0/1200011502754281/1200495858241492
- https://app.asana.com/0/1200011502754281/1200451265990936
- https://app.asana.com/0/1200011502754281/1200520309783654
> Refactoring sls logs & invoke

- src/cli/commands-cn/help.js
Added invoke info for all scf-related components
Related ticket: https://app.asana.com/0/1200011502754281/1200564578605216
> Add invoke info in all scf related components

- src/cli/commands-cn/help.js
Added stage help info in --help option for `deploy`, `dev`, `info`, `remove`
Related ticket: https://app.asana.com/0/1200011502754281/1200564578605224
> Add stage info in --help

- src/cli/commands-cn/runAll.js
- src/cli/utils.js
https://app.asana.com/0/1200011502754281/1200578828969034
> Better status report for multi instance project

- src/cli/commands-cn/help.js
- src/cli/commands-cn/invoke/index.js
- src/cli/commands-cn/logs.js
Add namespace and qualifier options for `sls invoke & logs`
Relate ticket: https://app.asana.com/0/1200011502754281/1200564578605229
> Add namespace and qualifier options

- src/cli/commands-cn/dev.js
- src/cli/commands-cn/invoke/index.js
- src/cli/commands-cn/utils.js
1. Not found path uses warning messge
2. Use `state` data when outputs is wrong
> fix: update dev mode api pararmeter

- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/commands-cn/utils.js
- src/cli/interactive-onboarding/cn.js
Close: [Improvement for CLI by Ke's review](https://app.asana.com/0/1200011502754281/1200637546882709/f)
> fix: improve code by review

- src/cli/commands-cn/run.js
Close: https://app.asana.com/0/1200011502754281/1200641178661047/f
> improve event for custom command

- src/cli/commands-cn/help.js
- src/cli/commands-cn/invoke/invoke-local/index.js
- src/cli/commands-cn/invoke/invoke-local/runPhp.js
- src/cli/commands-cn/invoke/invoke-local/utils.js
Close: https://app.asana.com/0/1200011502754281/1200710912169714/f
> feat: invoke local for php

- src/cli/commands-cn/runAll.js
- src/cli/utils.js
https://app.asana.com/0/1200011502754281/1200779233816531/f
> Terminate process when users meet permission issue

- src/cli/CLI.js
- src/cli/commands-cn/run.js
- src/cli/index.js
- src/cli/utils.js
Add a new error type to better display `type validation` errors
https://app.asana.com/0/1200011502754281/1200637546882728
> Add support for displaying type errors

- src/cli/commands-cn/run.js
Print type errors only when they exist
> Fix typeError not exist issue

- src/cli/CLI.js
Show basic error message earlier
> Update type error messages' order

- package.json
- src/cli/commands-cn/dev.js
- src/cli/commands-cn/init.js
- src/cli/commands-cn/invoke/index.js
- src/cli/commands-cn/invoke/invoke-local/index.js
- src/cli/commands-cn/logs.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/runAll.js
- src/cli/interactive-onboarding/cn.js
Close: https://app.asana.com/0/1200011502754281/1200844911571319/f
> fix: record the events for external error

- src/cli/CLI.js
- src/cli/commands-cn/help.js
- src/cli/commands-cn/run.js
Add `--noValidation` and `--noCache` support for deploy command.
Screenshot
Related ticket: https://app.asana.com/0/1200011502754281/1200844911571325
> Add --noValidation and --noCache support for deploy command

- CHANGELOG.md
- package.json
- src/cli/commands-cn/telemtry/index.js
Fix wrong metrics URL for Chinese users using online overseas CI services
> fix: fix wrong metrics URL for Chinese users

- src/cli/commands-cn/dev.js
- src/cli/commands-cn/init.js
- src/cli/commands-cn/invoke/index.js
- src/cli/commands-cn/invoke/invoke-local/index.js
- src/cli/commands-cn/logs.js
- src/cli/commands-cn/run.js
- src/cli/commands-cn/telemtry/generatePayload.js
- src/cli/commands-cn/telemtry/index.js
- src/cli/commands-cn/utils.js
- src/cli/interactive-onboarding/cn.js
Close: https://app.asana.com/0/1200011502754281/1201315882238108/f
> feat: improve cli error fields

- src/cli/commands-cn/utils.js
Closes https://app.asana.com/0/1200011502754281/1201300336822086/f
- `npm i @serverless/components@canary -g`
- `components init eggjs-starter(express-starter, koa-starter, nextjs-starter, nuxtjs-starter) --name example`
- `cd example`
- ` rm serverless.yml`
- `components deploy`: CLI will automatically generate a new `serverless.yml` for this project via the `http` component and deploy successfully
> feat: upgrade generateYMLForNodeProject on http component

- src/cli/commands-cn/utils.js
Closes https://app.asana.com/0/0/1201300336822086/1201371479968004/
> update name field for generate function

- CHANGELOG.md
- package.json
- Generate YML via Node project improvement for Chinese users
> release: 3.18.1

- CHANGELOG.md
- package.json
- src/cli/commands-cn/logs.js
Closes https://app.asana.com/0/1200011502754281/1201678086194154
> Stop polling logs when two errors happen in a row
